### ISSUE TITLE
How to configure Orphaned Items Strategy so that deleting a branch triggers an action soonish?

### ISSUE THREAD

**Issue by grahampfau** [jenkinsci/multibranch-action-triggers-plugin#16]
I have a test pipeline that I'm using to test this plugin. In `Orphaned Item Strategy` it has `Discard old items` checked and both `Days to keep old items` and `Max # of old items to keep` are both empty. When I close a PR (I'm doing things off of PRs) it shows the PR name struck through, like ~PR-17~, but my `Pipeline Delete Event` isn't run until I manually do something like `Scan Repository Now` that totally removes old items from Jenkins.

Is there a way to configure things so that my delete actions are run when the remote branch is deleted, or at least within a few hours after it is deleted?

**Comment by aytuncbeken** [comment]
Hi, 

This plugin is triggered when the delete event is occurred. Therefore two thing I can suggest for immediately deleting a branch when a PR is closed.
First uncheck the Discard Old Items option. Second, if possible, define a hook in the source repository system which is pointed to Jenkins for triggering Scanning when a branch/pr is deleted/created/closed/merged. 
If this is not possible, you can define "Periodically if not otherwise run" for auto scanning for every 1/5 minutes ( depending on your needs) .

Hopefully, this will help for solving your problem.

**Comment by aytuncbeken** [comment]
As this is not related to this plugins behavior, I am closing the issue.
